version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: inventorymanagementapp
      MYSQL_USER: tbless
      MYSQL_PASSWORD: 1234

  inventorymanagementapp:
    build: C:\Users\OLAITAN BLESSING\IdeaProjects\inventoryManagementApp
    container_name: spring-app-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/inventorymanagementapp
      SPRING_DATASOURCE_USERNAME: tbless
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - mysql

  adminer:
    image: adminer
    container_name: adminer-container
    ports:
      - "8081:8080"
    depends_on:
      - mysql
