version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 42HBdgFbHF4c4AE42cABDE5B15EAgc31
      MYSQL_DATABASE: inventorymanagementapp
      MYSQL_USER: tbless
      MYSQL_PASSWORD: 42HBdgFbHF4c4AE42cABDE5B15EAgc31

  inventorymanagementapp:
    build: C:\Users\OLAITAN BLESSING\IdeaProjects\inventoryManagementApp
    container_name: spring-app-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://root:42HBdgFbHF4c4AE42cABDE5B15EAgc31@viaduct.proxy.rlwy.net:35870/railway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 42HBdgFbHF4c4AE42cABDE5B15EAgc31
    depends_on:
      - mysql

